### ISSUE TITLE
Request a zeph's  private key

### ISSUE THREAD

**Issue by Apexlq** [pps-lab/zeph-artifact#2]
Could you give me a private key and AWS credentials? 
My email address is 2394040086@qq.com.

**Comment by nicolas-kuechler** [comment]
During the OSDI'21 artifact evaluation, we provided credentials to the reviewers.
Outside of this specific purpose, our credentials are not generally available.

However, you should be able to create your own credentials and use Zeph with them on AWS.
Alternatively, you can also run Zeph locally.
